[package]
name = "attribute_parse"
authors = ["The RefinedRust Developers and Contributors"]
license = "MIT"

edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
unicode-xid.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
