dump_borrowck_info=false
output_dir="./output"
log_dir = "./log"
shims = "rr_shims.json"
run_check = false
extra_specs = "extra_specs.v"
lib_load_paths = []
post_generation_hook = "patch output/minivec/generated/generated_code_minivec.v annotation_patch.patch"
